/*----------------------------------------------------------
MASV, HO TEN CAC THANH VIEN NHOM: Lê Trung Nguyên - 20120338
						  Ng? Duy Tính – 21120572
						  Lê Ti?n Phát – 21120520
					     	  Tr?n Bùi Thái S?n - 21120549
LAB: 04 - NHOM
NGAY: 31-5-2024
----------------------------------------------------------*/

CREATE DATABASE QLSVNhom;
GO

USE QLSVNhom
GO

DROP TABLE BANGDIEM;
DROP TABLE HOCPHAN;
DROP TABLE SINHVIEN;
DROP TABLE LOP;
DROP TABLE NHANVIEN;

CREATE TABLE NHANVIEN(
	MANV VARCHAR (20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR (20),
	LUONG VARBINARY(1000),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(1000) NOT NULL,
	PUBKEY VARCHAR(20),
	CONSTRAINT PK_NV PRIMARY KEY(MANV)  
)
GO

CREATE TABLE LOP(
	MALOP VARCHAR (20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR (20),
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
	--CONSTRAINT FK_LOP_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)
GO

CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR (20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(1000) NOT NULL,
	CONSTRAINT PK_SV PRIMARY KEY(MASV),
	CONSTRAINT FK_SV_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
)
GO

CREATE TABLE HOCPHAN(
	MAHP VARCHAR(20), 
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT,
	CONSTRAINT PK_HP PRIMARY KEY(MAHP)
)
GO

CREATE TABLE BANGDIEM(
	MASV NVARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(1000),
	CONSTRAINT PK_BD PRIMARY KEY (MASV, MAHP),
	CONSTRAINT FK_BD_SV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
	CONSTRAINT FK_BD_HP FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
)
GO