/*----------------------------------------------------------
MASV, HO TEN CAC THANH VIEN NHOM: Lê Trung Nguyên - 20120338
						  Ng? Duy Tính – 21120572
						  Lê Ti?n Phát – 21120520
					     	  Tr?n Bùi Thái S?n - 21120549
LAB: 04 - NHOM
NGAY: 31-5-2024
----------------------------------------------------------*/

USE QLSVNhom
GO

-- PROCEDURE INSERT NHAN VIEN
CREATE OR ALTER PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
@MANV VARCHAR(20),
@HOTEN NVARCHAR(100),
@EMAIL VARCHAR(20),
@LUONG VARBINARY(1000),
@TENDN NVARCHAR(100),
@MK VARBINARY(1000),
@PUB VARCHAR(20)
AS 
BEGIN
	INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @PUB);
END;
GO

-- SELECT ENCRYPTED INFOR OF EMP
CREATE OR ALTER PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
@TENDN NVARCHAR(100),
@MK VARBINARY(1000)
AS
BEGIN
	SELECT MANV, HOTEN, EMAIL, LUONG
	FROM NHANVIEN 
	WHERE TENDN = @TENDN AND @MK = @MK
END;
GO


DECLARE @HASH_MK VARBINARY(MAX);
SET @HASH_MK = 0x93c419df6040a069bbb8047f25231a1d66e211c2
EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', NULL, 'NVA', @HASH_MK, 'NV01PUB';

INSERT INTO LOP VALUES ('CNTT-K35', 'CONG NGHE THONG TIN K35', 'NV01');

INSERT INTO HOCPHAN VALUES ('CSC11115', N'An ninh m?ng', 4);
/*
						   ('CSC12001', N'An toàn và b?o m?t d? li?u trong h? th?ng thông tin', 4),
						   ('CSC15002', N'B?o m?t c? s? d? li?u', 4),
						   ('CSC15003', N'Mã hóa ?ng d?ng', 4);
						   */

/*
INSERT INTO SINHVIEN VALUES ('SV01', 'NGUYEN VAN A', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K35', 'SVA', NULL),
							('SV02', 'TRAN VAN B', '5/5/2003', '306A BPQ', 'KHMT-K35', 'SVB', NULL);

INSERT INTO BANGDIEM VALUES ('SV01', 'CSC11115', NULL)
INSERT INTO BANGDIEM VALUES ('SV01', 'CSC12001', NULL)
INSERT INTO BANGDIEM VALUES ('SV01', 'CSC15002', NULL)
INSERT INTO BANGDIEM VALUES ('SV01', 'CSC15003', NULL)
*/

SELECT* FROM NHANVIEN
SELECT* FROM BANGDIEM
SELECT* FROM LOP
SELECT* FROM HOCPHAN